name: build

on:
  push:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build CacheLib CI image
        run: docker build -t cachelib-ci cachelib-ci

      - name: Deploy CacheLib CI image
        run: |
          docker tag cachelib-ci ghcr.io/$GITHUB_ACTOR/cachelib-ci
          docker push            ghcr.io/$GITHUB_ACTOR/cachelib-ci
